from django.http import HttpResponse
from django.template import loader


def index(request):
    template = loader.get_template(template_name="index.html")

    # Get the 'csp_nonce' value generated by middleware and use it in the template.
    context = {
        'csp_nonce': getattr(request, 'csp_nonce')
    }
    return HttpResponse(content=template.render(context, request))