---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    app: dvwa
spec:
  containers:
  - name: dvwa
    image: demo-registry:5000/web-dvwa:v1.0.0

---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: NodePort
  selector:
    app: dvwa
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
