apiVersion: policies.kyverno.io/v1
kind: ImageValidatingPolicy
metadata:
  name: check-images
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: ['']
        apiVersions: ['v1']
        operations: ['CREATE']
        resources: ['pods']
  matchImageReferences:
    - glob: "*"
  attestors:
    - name: cosign 
      cosign:
        key: 
          data:
            | 
            -----BEGIN PUBLIC KEY-----
            MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEGHHI1WgulOlC6TLXZURascLO9zmN
            EF0fZkPbu7rJd0XAHdmAjl0pW6W7n3lCGqK4AzJAKEOmC/xAaC8fkiCMsA==
            -----END PUBLIC KEY-----
  attestations:
    - name: sbom 
      referrer: 
        type: sbom/cyclonedx
      attestors:
        - cosign
  validations:
    - expression: images.containers.map(image, verifyImageSignatures(image, [attestors.cosign])).all(e ,e > 0)
      message: All images must be signed by a trusted agent.
    - expression: has(attestations.sbom)
      message: All images must have a SBOM.
