---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: block-affected-vex
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: check-vex-not-affected
      match:
        any:
          - resources:
              kinds:
                - Pod
      verifyImages:
        - imageReferences:
            - "*"
          attestations:
            - type: https://openvex.dev/ns/v0.2.0
              conditions:
                - all:
                    - key: "{{ attestation.payload.statements[].status }}"
                      operator: AllNotIn
                      value:
                        - affected
