apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: block-affected-vex
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: check-vex-not-affected
      match:
        any:
          - resources:
              kinds:
                - Pod
      verifyImages:
        - imageReferences:
            - "*"
          attestors:
            - entries:
                - keys:
                    publicKeys: |
                      -----BEGIN PUBLIC KEY-----
                      -----END PUBLIC KEY-----
          attestations:
            - predicateType: https://openvex.dev/ns
              conditions:
                - all:
                    - key: "{{ attestation.payload.statements[].status }}"
                      operator: AllNotIn
                      value:
                        - affected
