apiVersion: policies.kyverno.io/v1
kind: ImageValidatingPolicy
metadata:
  name: check-images
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: ['']
        apiVersions: ['v1']
        operations: ['CREATE']
        resources: ['pods']
  matchImageReferences:
    - glob: "*"
  attestors:
    - name: cosign 
      cosign:
        key: 
          data:
            | 
            -----BEGIN PUBLIC KEY-----
            MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEx/uODzddcy32InzeN7y9gInxpl48
            iCGH6faPh/p2aygwz796CXCh2dHXL3YtzsVSMS2DNlmruKB0ZoCuhgBgOQ==
            -----END PUBLIC KEY-----
  attestations:
    - name: sbom
      intoto:
        type: https://cyclonedx.org/bom
    - name: scan
      intoto:
        type: https://cosign.sigstore.dev/attestation/vuln/v1
  validations:
    - expression: images.containers.map(image, verifyImageSignatures(image, [attestors.cosign])).all(e ,e > 0)
      message: All images must be signed by a trusted agent.
    - expression: has(attestations.sbom)
      message: All images must have a SBOM.
    - expression: images.containers.map(image, verifyAttestationSignatures(image, attestations.sbom, [attestors.cosign])).all(e, e > 0)
      message: All SBOMs must be signed by a trusted agent.
    - expression: has(attestations.scan)
      message: All images must have a scan.
    - expression: images.containers.map(image, verifyAttestationSignatures(image, attestations.scan, [attestors.cosign])).all(e, e > 0)
      message: All scans must be signed by a trusted agent.
    - expression: >
        images.containers.map(image, 
          extractPayload(image, attestations.scan).predicate.scanner.result.matches
          .filter(m, m.vulnerability.severity == "Critical").size() <= 326
        ).all(e, e)
      message: Images with greater than or equal to 326 critical CVEs are prohibited.
