---
apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: sonic
  namespace: sonic
spec:
  network:
    expose:
      - service: sonic
        selector:
          app.kubernetes.io/name: sonic
        gateway: tenant
        host: sonic
        port: 8888
  sso:
    - name: sonic SSO
      clientId: uds-core-sonic
      redirectUris:
        - "https://sonic.uds.dev/login"
      enableAuthserviceSelector:
        app.kubernetes.io/name: sonic
      groups:
        anyOf:
          - "/UDS Core/Admin"
  monitor:
    - selector:
        app.kubernetes.io/name: sonic
      targetPort: 9898
      portName: http
      description: "sonic metrics"
      kind: PodMonitor
